# The Docker image that will be used to build your app
image: rust:1.82.0

cache:
  paths:
    - .cargo

pages:
  before_script:
    - cargo install trunk
    - rustup target add wasm32-unknown-unknown
  script:
    - trunk build --release --public-url $CI_PAGES_URL
  artifacts:
    paths:
      - dist
  publish: dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
