# The Docker image that will be used to build your app
image: rust:1.82.0
pages:
  before_script:
    - cargo install trunk
  script:
    - trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
  artifacts:
    paths:
      - dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
