# The Docker image that will be used to build your app
image: rust:1.82.0

cache:
  paths:
    - .cargo
    - node_modules

pages:
  before_script:
    - cargo install trunk
    - rustup target add wasm32-unknown-unknown
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt-get install -y nodejs
    - npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
  script:
    - trunk build --release --public-url $CI_PAGES_URL
  artifacts:
    paths:
      - dist
  publish: dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
