# The Docker image that will be used to build your app
image: rust:1.88.0

cache:
  paths:
    - .cargo
    - node_modules

pages:
  before_script:
    - git clone https://gitlab.com/rigz_lang/rigz.git
    - apt-get update -y && apt-get install -y --no-install-recommends curl clang
    - cargo install trunk
    - rustup target add wasm32-unknown-unknown
    - curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt-get install -y nodejs
    - npm ci
    - npm install tailwindcss @tailwindcss/cli
  script:
    - trunk build --release --public-url https://repl.rigz-lang.org/
  artifacts:
    paths:
      - dist
  publish: dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
